version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: "daily"
